# Generated by Django 6.1 on 2026-08-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_portal', '0002_alter_application_applicant_alter_application_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
