# Generated by Django 6.1 on 2026-08-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job_notification_apply_organization_job_organization_and_more'),
        ('opportunity_portal', '0003_delete_application'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_user_job_bookmark',
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunity_portal.job'),
        ),
        migrations.AddField(
            model_name='apply',
            name='phone',
            field=models.CharField(default='18000000000', max_length=20),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='job',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
